-- CreateTable
-- Baseline Postgres migration for Cold-Pilot.
-- Generated by hand-translating the final state of schema.prisma (after all
-- 24 prior SQLite migrations were squashed) into native Postgres DDL, since
-- the old migration history was written entirely in SQLite dialect (DATETIME
-- columns, PRAGMA statements, table-rebuild ALTER patterns) and cannot run
-- against Postgres as-is.

CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT,
    "email" TEXT NOT NULL,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,
    "password" TEXT,
    "role" TEXT NOT NULL DEFAULT 'user',
    "completedOnboarding" BOOLEAN NOT NULL DEFAULT false,
    "onboardingSource" TEXT,
    "onboardingWebsite" TEXT,
    "onboardingGoals" TEXT,
    "totpSecret" TEXT,
    "plan" TEXT NOT NULL DEFAULT 'free',
    "leadLimitOverride" INTEGER,
    "billingCurrency" TEXT NOT NULL DEFAULT 'NGN',
    "creditBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "freeCreditReserve" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "signupCreditsGranted" BOOLEAN NOT NULL DEFAULT false,
    "trialEndsAt" TIMESTAMP(3),
    "planExpiresAt" TIMESTAMP(3),
    "planReminderSentDays" INTEGER NOT NULL DEFAULT 0,
    "lastBillingVisitAt" TIMESTAMP(3),
    "billingFollowUpSentAt" TIMESTAMP(3),
    "founderWelcomeSentAt" TIMESTAMP(3),
    "founderTrialExpiringSentAt" TIMESTAMP(3),
    "founderTrialExpiredSentAt" TIMESTAMP(3),
    "onboardingNudgesSent" INTEGER NOT NULL DEFAULT 0,
    "bachsCustomerId" TEXT,
    "bachsSubscriptionId" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "trialVoided" BOOLEAN NOT NULL DEFAULT false,
    "trialVoidReason" TEXT,
    "trialVoidedAt" TIMESTAMP(3),
    "riskScore" INTEGER NOT NULL DEFAULT 0,
    "riskFlags" TEXT NOT NULL DEFAULT '[]',
    "riskStatus" TEXT NOT NULL DEFAULT 'none',
    "deviceFingerprint" TEXT,
    "signupIp" TEXT,
    "signupCountry" TEXT,
    "signupSource" TEXT,
    "signupReferrer" TEXT,
    "signupUtmSource" TEXT,
    "signupUtmMedium" TEXT,
    "signupUtmCampaign" TEXT,
    "signupUserAgent" TEXT,
    "reviewedAt" TIMESTAMP(3)
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

CREATE TABLE "MailboxIdentity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "firstSeenUserId" TEXT NOT NULL,
    "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastConnectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "disconnectedAt" TIMESTAMP(3),
    "disconnectCount" INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX "MailboxIdentity_provider_providerAccountId_key" ON "MailboxIdentity"("provider", "providerAccountId");
CREATE INDEX "MailboxIdentity_firstSeenUserId_idx" ON "MailboxIdentity"("firstSeenUserId");
CREATE INDEX "MailboxIdentity_email_idx" ON "MailboxIdentity"("email");

CREATE TABLE "SignupSignal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "deviceFingerprint" TEXT,
    "ip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "SignupSignal_deviceFingerprint_idx" ON "SignupSignal"("deviceFingerprint");
CREATE INDEX "SignupSignal_ip_idx" ON "SignupSignal"("ip");

CREATE TABLE "BlockedSignal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "BlockedSignal_type_value_key" ON "BlockedSignal"("type", "value");
CREATE INDEX "BlockedSignal_type_idx" ON "BlockedSignal"("type");

CREATE TABLE "LoginAttempt" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "ip" TEXT,
    "userAgent" TEXT,
    "success" BOOLEAN NOT NULL DEFAULT false,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "LoginAttempt_email_idx" ON "LoginAttempt"("email");
CREATE INDEX "LoginAttempt_ip_idx" ON "LoginAttempt"("ip");
CREATE INDEX "LoginAttempt_createdAt_idx" ON "LoginAttempt"("createdAt");

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT
);
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

CREATE TABLE "UserSession" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "sid" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "UserSession_sid_key" ON "UserSession"("sid");
CREATE INDEX "UserSession_userId_idx" ON "UserSession"("userId");

-- CreateTable
CREATE TABLE "EmailAccount" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "smtpHost" TEXT,
    "smtpPort" INTEGER,
    "smtpUser" TEXT,
    "smtpPass" TEXT,
    "imapHost" TEXT,
    "imapPort" INTEGER,
    "imapUser" TEXT,
    "imapPass" TEXT,
    "gmailClientId" TEXT,
    "gmailSecret" TEXT,
    "gmailToken" TEXT,
    "microsoftToken" TEXT,
    "microsoftRefreshToken" TEXT,
    "displayName" TEXT,
    "domain" TEXT,
    "warmupEnabled" BOOLEAN NOT NULL DEFAULT false,
    "warmupBase" INTEGER NOT NULL DEFAULT 2,
    "warmupIncrease" INTEGER NOT NULL DEFAULT 2,
    "warmupMax" INTEGER NOT NULL DEFAULT 10,
    "warmupDays" INTEGER NOT NULL DEFAULT 127,
    "warmupFilterTag" TEXT NOT NULL DEFAULT '',
    "disableSlowWarmup" BOOLEAN NOT NULL DEFAULT false,
    "warmupReplyRate" INTEGER NOT NULL DEFAULT 30,
    "readEmulation" BOOLEAN NOT NULL DEFAULT false,
    "warmupOpenRate" INTEGER NOT NULL DEFAULT 100,
    "warmupSpamProtection" INTEGER NOT NULL DEFAULT 100,
    "warmupMarkImportant" INTEGER NOT NULL DEFAULT 0,
    "customTrackingDomain" TEXT NOT NULL DEFAULT '',
    "warmupCustomTrackingDomain" BOOLEAN NOT NULL DEFAULT false,
    "warmupStartTime" TEXT NOT NULL DEFAULT '08:00',
    "warmupEndTime" TEXT NOT NULL DEFAULT '17:00',
    "minWaitTime" INTEGER NOT NULL DEFAULT 60,
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "warmupAiEnabled" BOOLEAN NOT NULL DEFAULT true,
    "healthScore" DOUBLE PRECISION NOT NULL DEFAULT 100,
    "healthState" TEXT NOT NULL DEFAULT 'healthy',
    "warmupBounceRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "warmupBounceFlag" BOOLEAN NOT NULL DEFAULT false,
    "isPaused" BOOLEAN NOT NULL DEFAULT false,
    "warmupWeek" INTEGER NOT NULL DEFAULT 1,
    "currentDailyVolume" INTEGER NOT NULL DEFAULT 5,
    "targetDailyVolume" INTEGER NOT NULL DEFAULT 50,
    "dailySendLimit" INTEGER NOT NULL DEFAULT 30,
    "warmupStartedAt" TIMESTAMP(3),
    "lastHealthCheckAt" TIMESTAMP(3),
    "lastSentUid" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3)
);

-- CreateTable
CREATE TABLE "WarmupLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "senderMailboxId" TEXT,
    "senderInboxId" TEXT,
    "seedMailboxId" TEXT,
    "seedInboxId" TEXT,
    "messageId" TEXT,
    "subject" TEXT,
    "bodyPreview" TEXT,
    "bodyHtml" TEXT,
    "sentAt" TIMESTAMP(3),
    "receivedAt" TIMESTAMP(3),
    "repliedAt" TIMESTAMP(3),
    "foundInSpam" BOOLEAN NOT NULL DEFAULT false,
    "rescuedFromSpam" BOOLEAN NOT NULL DEFAULT false,
    "markedImportant" BOOLEAN NOT NULL DEFAULT false,
    "replyReceived" BOOLEAN NOT NULL DEFAULT false,
    "bounceType" TEXT,
    "status" TEXT NOT NULL DEFAULT 'sent',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "WarmupContent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "senderMailboxId" TEXT NOT NULL,
    "seedMailboxId" TEXT,
    "seedInboxId" TEXT,
    "contentHash" TEXT NOT NULL,
    "subjectPreview" TEXT NOT NULL,
    "bodyPreview" TEXT NOT NULL,
    "contentSource" TEXT NOT NULL DEFAULT 'templates',
    "usedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "WarmupContent_senderMailboxId_seedMailboxId_contentHash_key" ON "WarmupContent"("senderMailboxId", "seedMailboxId", "contentHash");
CREATE UNIQUE INDEX "WarmupContent_senderMailboxId_seedInboxId_contentHash_key" ON "WarmupContent"("senderMailboxId", "seedInboxId", "contentHash");
CREATE INDEX "WarmupContent_senderMailboxId_idx" ON "WarmupContent"("senderMailboxId");

CREATE TABLE "Campaign" (
    "accountIds" TEXT NOT NULL DEFAULT '[]',
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "openTracking" BOOLEAN NOT NULL DEFAULT false,
    "clickTracking" BOOLEAN NOT NULL DEFAULT false,
    "conversionValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "dailySendLimit" INTEGER NOT NULL DEFAULT 30,
    "slowRamp" BOOLEAN NOT NULL DEFAULT false,
    "rampStart" TIMESTAMP(3),
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "noEndDate" BOOLEAN NOT NULL DEFAULT true,
    "stopOnReply" BOOLEAN NOT NULL DEFAULT true,
    "plainTextOnly" BOOLEAN NOT NULL DEFAULT false,
    "firstEmailPlainText" BOOLEAN NOT NULL DEFAULT false,
    "crmOwner" TEXT NOT NULL DEFAULT '',
    "customTags" TEXT NOT NULL DEFAULT '[]',
    "minTimeBetween" INTEGER NOT NULL DEFAULT 15,
    "randomExtraTime" INTEGER NOT NULL DEFAULT 9,
    "maxNewLeads" INTEGER,
    "prioritizeNewLeads" BOOLEAN NOT NULL DEFAULT false,
    "providerMatching" BOOLEAN NOT NULL DEFAULT false,
    "espRouting" BOOLEAN NOT NULL DEFAULT false,
    "stopOnCompanyReply" BOOLEAN NOT NULL DEFAULT false,
    "stopOnAutoReply" BOOLEAN NOT NULL DEFAULT false,
    "unsubscribeHeader" BOOLEAN NOT NULL DEFAULT true,
    "enableRiskyEmails" BOOLEAN NOT NULL DEFAULT false,
    "disableBounceProtect" BOOLEAN NOT NULL DEFAULT false,
    "ccAddresses" TEXT NOT NULL DEFAULT '',
    "bccAddresses" TEXT NOT NULL DEFAULT '',
    "nextAllowedSendAt" TIMESTAMP(3),
    "resumeOnFunding" BOOLEAN NOT NULL DEFAULT false,
    "deletedAt" TIMESTAMP(3),
    "lastCheckedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "CampaignSchedule" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "campaignId" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'New schedule',
    "startTime" TEXT NOT NULL DEFAULT '09:00',
    "endTime" TEXT NOT NULL DEFAULT '18:00',
    "timezone" TEXT NOT NULL DEFAULT 'America/New_York',
    "days" TEXT NOT NULL DEFAULT '[true,true,true,true,true,false,false]',
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "CampaignStep" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "campaignId" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "subject" TEXT,
    "bodyHtml" TEXT,
    "delayDays" INTEGER,
    "delayUnit" TEXT NOT NULL DEFAULT 'days',
    "conditions" TEXT,
    "templateId" TEXT
);

-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "campaignId" TEXT,
    "email" TEXT NOT NULL,
    "firstName" TEXT,
    "lastName" TEXT,
    "company" TEXT,
    "title" TEXT,
    "phone" TEXT,
    "personalization" TEXT,
    "website" TEXT,
    "location" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "currentStep" INTEGER NOT NULL DEFAULT 0,
    "sendingAccountId" TEXT,
    "lastSentAt" TIMESTAMP(3),
    "lastReadAt" TIMESTAMP(3),
    "notes" TEXT,
    "customFields" TEXT,
    "verificationStatus" TEXT,
    "verificationReason" TEXT,
    "provider" TEXT,
    "verifiedAt" TIMESTAMP(3),
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "EmailLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "leadId" TEXT NOT NULL,
    "campaignStepId" TEXT,
    "emailAccountId" TEXT,
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "subject" TEXT,
    "bodyHtml" TEXT,
    "threadId" TEXT,
    "messageId" TEXT,
    "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "openedAt" TIMESTAMP(3),
    "repliedAt" TIMESTAMP(3),
    "clickedAt" TIMESTAMP(3),
    "error" TEXT,
    "bounceCategory" TEXT
);

CREATE TABLE "Pipeline" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "stages" TEXT NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Deal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "pipelineId" TEXT NOT NULL,
    "leadId" TEXT,
    "name" TEXT NOT NULL,
    "value" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "stage" TEXT NOT NULL DEFAULT 'interested',
    "status" TEXT NOT NULL DEFAULT 'open',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Task" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "dealId" TEXT,
    "title" TEXT NOT NULL,
    "done" BOOLEAN NOT NULL DEFAULT false,
    "dueDate" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Integration" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "label" TEXT,
    "config" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "Integration_userId_provider_key" ON "Integration"("userId", "provider");

CREATE TABLE "Webhook" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "events" TEXT NOT NULL DEFAULT '["open","click","reply","bounce"]',
    "secret" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastStatus" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "ApiKey" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "scopes" TEXT NOT NULL DEFAULT 'read',
    "lastUsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "ApiKey_key_key" ON "ApiKey"("key");

CREATE TABLE "Notification" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "link" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Suppression" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'manual',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "Suppression_userId_email_key" ON "Suppression"("userId", "email");

-- CreateTable
CREATE TABLE "Template" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "bodyHtml" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

-- CreateIndex
CREATE TABLE "DomainReputation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "domain" TEXT NOT NULL,
    "totalSent" INTEGER NOT NULL DEFAULT 0,
    "totalBounced" INTEGER NOT NULL DEFAULT 0,
    "bounceRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "lastBouncedAt" TIMESTAMP(3),
    "lastAlertAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "DomainReputation_domain_key" ON "DomainReputation"("domain");

-- CreateIndex
CREATE TABLE "BounceEvent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "domain" TEXT NOT NULL,
    "errorCode" TEXT,
    "bounceType" TEXT NOT NULL,
    "reason" TEXT,
    "emailAccountId" TEXT,
    "leadId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE TABLE "SchedulerLock" (
    "key" TEXT NOT NULL PRIMARY KEY,
    "token" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

-- CreateIndex
CREATE TABLE "CreditTransaction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "reason" TEXT NOT NULL,
    "refId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "CreditTransaction_userId_idx" ON "CreditTransaction"("userId");

-- CreateIndex
CREATE TABLE "BachsWebhookEvent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL,
    "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "BachsWebhookEvent_processedAt_idx" ON "BachsWebhookEvent"("processedAt");

CREATE TABLE "PaymentEvent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "amount" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'NGN',
    "plan" TEXT,
    "subscriptionId" TEXT,
    "providerEventId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "PaymentEvent_providerEventId_key" ON "PaymentEvent"("providerEventId");
CREATE INDEX "PaymentEvent_userId_idx" ON "PaymentEvent"("userId");
CREATE INDEX "PaymentEvent_type_idx" ON "PaymentEvent"("type");
CREATE INDEX "PaymentEvent_createdAt_idx" ON "PaymentEvent"("createdAt");

CREATE TABLE "GlobalLeadIntel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "verdict" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "hitCount" INTEGER NOT NULL DEFAULT 1,
    "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "GlobalLeadIntel_email_key" ON "GlobalLeadIntel"("email");
CREATE INDEX "GlobalLeadIntel_expiresAt_idx" ON "GlobalLeadIntel"("expiresAt");
CREATE INDEX "GlobalLeadIntel_reason_idx" ON "GlobalLeadIntel"("reason");

CREATE TABLE "SeedInbox" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'other',
    "smtpHost" TEXT,
    "smtpPort" INTEGER,
    "smtpUser" TEXT,
    "smtpPass" TEXT,
    "imapHost" TEXT,
    "imapPort" INTEGER,
    "imapUser" TEXT,
    "imapPass" TEXT,
    "gmailToken" TEXT,
    "microsoftToken" TEXT,
    "microsoftRefreshToken" TEXT,
    "displayName" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "tags" TEXT NOT NULL DEFAULT '[]',
    "filterTag" TEXT NOT NULL DEFAULT '',
    "healthScore" DOUBLE PRECISION NOT NULL DEFAULT 100,
    "healthState" TEXT NOT NULL DEFAULT 'healthy',
    "lastUsedAt" TIMESTAMP(3),
    "note" TEXT,
    "dailyTarget" INTEGER NOT NULL DEFAULT 10,
    "warmupBase" INTEGER NOT NULL DEFAULT 2,
    "warmupIncrease" INTEGER NOT NULL DEFAULT 2,
    "warmupStartedAt" TIMESTAMP(3),
    "scheduleStart" TEXT NOT NULL DEFAULT '09:00',
    "scheduleEnd" TEXT NOT NULL DEFAULT '17:00',
    "minWaitMinutes" INTEGER NOT NULL DEFAULT 10,
    "replyRate" INTEGER NOT NULL DEFAULT 75,
    "openRate" INTEGER NOT NULL DEFAULT 100,
    "spamProtection" INTEGER NOT NULL DEFAULT 100,
    "markImportant" INTEGER NOT NULL DEFAULT 10,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "SeedInbox_email_key" ON "SeedInbox"("email");
CREATE INDEX "SeedInbox_status_idx" ON "SeedInbox"("status");
CREATE INDEX "SeedInbox_email_idx" ON "SeedInbox"("email");

CREATE TABLE "WaitlistEntry" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL DEFAULT '',
    "email" TEXT NOT NULL,
    "source" TEXT NOT NULL DEFAULT 'waitlist',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "WaitlistEntry_email_key" ON "WaitlistEntry"("email");
CREATE INDEX "WaitlistEntry_createdAt_idx" ON "WaitlistEntry"("createdAt");

CREATE TABLE "ChatMessage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "byAdmin" BOOLEAN NOT NULL DEFAULT false,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "ChatMessage_userId_createdAt_idx" ON "ChatMessage"("userId", "createdAt");
CREATE INDEX "ChatMessage_createdAt_idx" ON "ChatMessage"("createdAt");

CREATE TABLE "ChatSettings" (
    "userId" TEXT NOT NULL PRIMARY KEY,
    "aiDisabled" BOOLEAN NOT NULL DEFAULT false,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============ Foreign keys (added after all tables exist) ============

ALTER TABLE "MailboxIdentity" ADD CONSTRAINT "MailboxIdentity_firstSeenUserId_fkey" FOREIGN KEY ("firstSeenUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SignupSignal" ADD CONSTRAINT "SignupSignal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserSession" ADD CONSTRAINT "UserSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmailAccount" ADD CONSTRAINT "EmailAccount_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "WarmupLog" ADD CONSTRAINT "WarmupLog_senderMailboxId_fkey" FOREIGN KEY ("senderMailboxId") REFERENCES "EmailAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WarmupLog" ADD CONSTRAINT "WarmupLog_senderInboxId_fkey" FOREIGN KEY ("senderInboxId") REFERENCES "SeedInbox"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WarmupLog" ADD CONSTRAINT "WarmupLog_seedMailboxId_fkey" FOREIGN KEY ("seedMailboxId") REFERENCES "EmailAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WarmupLog" ADD CONSTRAINT "WarmupLog_seedInboxId_fkey" FOREIGN KEY ("seedInboxId") REFERENCES "SeedInbox"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "WarmupContent" ADD CONSTRAINT "WarmupContent_senderMailboxId_fkey" FOREIGN KEY ("senderMailboxId") REFERENCES "EmailAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WarmupContent" ADD CONSTRAINT "WarmupContent_seedMailboxId_fkey" FOREIGN KEY ("seedMailboxId") REFERENCES "EmailAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WarmupContent" ADD CONSTRAINT "WarmupContent_seedInboxId_fkey" FOREIGN KEY ("seedInboxId") REFERENCES "SeedInbox"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CampaignSchedule" ADD CONSTRAINT "CampaignSchedule_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CampaignStep" ADD CONSTRAINT "CampaignStep_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Lead" ADD CONSTRAINT "Lead_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "EmailLog" ADD CONSTRAINT "EmailLog_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmailLog" ADD CONSTRAINT "EmailLog_emailAccountId_fkey" FOREIGN KEY ("emailAccountId") REFERENCES "EmailAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Pipeline" ADD CONSTRAINT "Pipeline_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Deal" ADD CONSTRAINT "Deal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Deal" ADD CONSTRAINT "Deal_pipelineId_fkey" FOREIGN KEY ("pipelineId") REFERENCES "Pipeline"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Deal" ADD CONSTRAINT "Deal_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Task" ADD CONSTRAINT "Task_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "Deal"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Integration" ADD CONSTRAINT "Integration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Webhook" ADD CONSTRAINT "Webhook_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Suppression" ADD CONSTRAINT "Suppression_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Template" ADD CONSTRAINT "Template_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "BounceEvent" ADD CONSTRAINT "BounceEvent_emailAccountId_fkey" FOREIGN KEY ("emailAccountId") REFERENCES "EmailAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BounceEvent" ADD CONSTRAINT "BounceEvent_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "CreditTransaction" ADD CONSTRAINT "CreditTransaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentEvent" ADD CONSTRAINT "PaymentEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ChatSettings" ADD CONSTRAINT "ChatSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
